import type { BoardroomReport, ConsensusScore } from "./types";

// ============================================================================
// Pure Markdown serializer for a BoardroomReport.
// No server-only imports — safe to use on both client and server (copy /
// download in the browser, export endpoint on the server).
// ============================================================================

function scoreRow(label: string, d: { value: number; justification: string }): string {
  return `| ${label} | **${d.value}/100** | ${d.justification} |`;
}

function list(items: string[]): string {
  return items.map((i) => `- ${i}`).join("\n");
}

export function reportToMarkdown(report: BoardroomReport): string {
  const { idea, consensus, scenarios, recommendation, assessments, debate } = report;
  const c: ConsensusScore = consensus;
  const date = new Date(report.createdAt).toISOString().slice(0, 10);

  const closings = debate.filter((m) => m.phase === "closing");
  const challenges = debate.filter((m) => m.phase === "challenge");

  return `# Boardroom AI — Decision Report

> _"Where AI leaders debate, challenge, and decide."_

**Idea:** ${idea.title}  
**Generated:** ${date}  
**Engine mode:** ${report.mode === "llm" ? "LLM" : "Demo (mock)"}

---

## 🏛️ Final Verdict: ${recommendation.verdict}

**${recommendation.executiveSummary}**

${recommendation.reasoning}

**What to do next:** ${recommendation.whatToDoNext}

---

## 💡 Idea Summary

| Field | Detail |
| --- | --- |
| **Problem** | ${idea.problem} |
| **Target users** | ${idea.targetUsers} |
| **Solution** | ${idea.solution} |
| **Business model** | ${idea.businessModel} |
| **Stage** | ${idea.stage} |

---

## 📊 Consensus Scores

| Dimension | Score | Why |
| --- | --- | --- |
${scoreRow("Market Potential", c.marketPotential)}
${scoreRow("Technical Feasibility", c.technicalFeasibility)}
${scoreRow("Business Viability", c.businessViability)}
${scoreRow("Risk Level (higher = riskier)", c.riskLevel)}
${scoreRow("Innovation", c.innovation)}
${scoreRow("Execution Difficulty (higher = harder)", c.executionDifficulty)}
${scoreRow("Overall Confidence", c.overallConfidence)}

### ✅ Top Strengths
${list(c.strengths)}

### ⚠️ Top Weaknesses
${list(c.weaknesses)}

### 🚨 Main Risks
${list(c.risks)}

### 🔬 Assumptions to Validate
${list(c.assumptionsToValidate)}

### 🧭 Recommended Next Steps
${list(c.recommendedNextSteps)}

---

## 🗣️ Boardroom Debate Highlights

### Challenges exchanged
${challenges.map((m) => `- **${m.agentName} → ${m.challengeTo}:** ${m.message}`).join("\n")}

### Final stances
${closings
  .map((m) => `- **${m.agentName} (${m.role}) — _${m.stance}_, ${m.confidence}% confidence:** ${m.message}`)
  .join("\n")}

### Per-agent assessment
${assessments
  .map((a) => `- **${a.agentName} (${a.role})** — _${a.stance}_\n  - Strength: ${a.topStrength}\n  - Risk: ${a.topRisk}`)
  .join("\n")}

---

## 🔮 Future Simulations

${scenarios
  .map(
    (s) => `### ${s.type} — ${s.headline} (${s.probability}% likely)
- **6 months:** ${s.sixMonths}
- **12 months:** ${s.twelveMonths}
- **Success drivers:** ${s.successDrivers.join("; ")}
- **Failure drivers:** ${s.failureDrivers.join("; ")}
- **Strategic advice:** ${s.strategicAdvice}`,
  )
  .join("\n\n")}

---

## 🎯 Final Recommendation

**Verdict:** ${recommendation.verdict}

${recommendation.consensusExplanation}

### Action Items
${list(recommendation.actionItems)}

### Experiments to Validate
${list(recommendation.experiments)}

### Suggested MVP Features
${list(recommendation.mvpFeatures)}

### Pitch Positioning
> ${recommendation.pitchPositioning}

---

_Generated by Boardroom AI — an AI executive council that makes ideas survive debate before giving a recommendation._
`;
}

export function reportFilename(report: BoardroomReport): string {
  const slug = report.idea.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "boardroom-report";
  return `boardroom-${slug}.md`;
}
